### ISSUE TITLE
求助：使用go语言调用grpc接口，证书认证失败，报错：x509: certificate relies on legacy Common Name field, use SANs instead

### ISSUE THREAD

**Issue by tanzhanhui** [WLwind/grpc_demo#6]
go代码如下：

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"flag"
	"log"
	"os"
	"time"

	"cyberdoggrpc/dogproto"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

var addr = flag.String("addr", "192.168.31.114:50052", "the address to connect to")

func callSkill(client dogproto.GrpcAppClient, code string) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	_, err := client.SendMsg(ctx, &dogproto.SendRequest{})
	if err != nil {
		log.Fatalf("client.UnaryEcho(_) = _, %v: ", err)
	}
	//fmt.Println("UnaryEcho: ", resp.Message)
}

func main() {
	flag.Parse()

	cert, err := tls.LoadX509KeyPair("cert/client-cert.pem", "cert/client-key.pem")
	if err != nil {
		log.Fatalf("failed to load client cert: %v", err)
	}

	ca := x509.NewCertPool()
	caFilePath := "cert/ca-cert.pem"
	caBytes, err := os.ReadFile(caFilePath)
	if err != nil {
		log.Fatalf("failed to read ca cert %q: %v", caFilePath, err)
	}
	if ok := ca.AppendCertsFromPEM(caBytes); !ok {
		log.Fatalf("failed to parse %q", caFilePath)
	}

	tlsConfig := &tls.Config{
		ServerName:   "cyberdog2.server",
		Certificates: []tls.Certificate{cert},
		RootCAs:      ca,
	}

	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)))
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()

	callSkill(dogproto.NewGrpcAppClient(conn), "111")
}

**Comment by WLwind** [comment]
我们没有用Go语言进行过测试，只用C++和Python语言进行过测试，可以正常和Cyberdog2进行通信，说明通信功能正常。请检查Go语言gRPC的调用方式是否正确。

**Comment by WLwind** [comment]
请自行用Go语言验证

**Comment by WLwind** [comment]
请自行用Go语言验证
